Document: picodrive
Title: Debian picodrive Manual
Author: <insert document author here>
Abstract: This manual describes what picodrive is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/picodrive/picodrive.sgml.gz

Format: postscript
Files: /usr/share/doc/picodrive/picodrive.ps.gz

Format: text
Files: /usr/share/doc/picodrive/picodrive.text.gz

Format: HTML
Index: /usr/share/doc/picodrive/html/index.html
Files: /usr/share/doc/picodrive/html/*.html

  
